name: myparflowenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - geopandas
  - rasterio
  - matplotlib
  - numpy
  - pip
  - pip:
    - git+https://github.com/parflow/parflowio.git
    - git+https://github.com/parflow/pftools.git
    - -e .
